### PR TITLE
Set the number of default instances to 3

### PR DESCRIPTION
**Pull request by fsat**

### CODE REVIEW

**Comment by fsat** [comment]
Manual test completed successfully.

The default agent instance for JVM-based sandbox is now increased to 3.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ sandbox run 2.0.0-rc.3 -f visualization
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance 0 on 192.168.10.1..
Starting ConductR agent instance 0 on 192.168.10.1..
Starting ConductR agent instance 1 on 192.168.10.2..
Starting ConductR agent instance 2 on 192.168.10.3..
Waiting for ConductR to start...
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/eslite-v1-c4acb219a37ce782222b94138987905f6c41be956b0cfe0156c96bdada7a596a.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle c4acb219a37ce782222b94138987905f waiting to be installed
Bundle c4acb219a37ce782222b94138987905f installed
Bundle loaded.
Bundle run request sent.
Bundle c4acb219a37ce782222b94138987905f waiting to reach expected scale 1
Bundle c4acb219a37ce782222b94138987905f has scale 0, expected 1..
Bundle c4acb219a37ce782222b94138987905f expected scale 1 is met
|------------------------------------------------|
| Starting visualization feature                 |
|------------------------------------------------|
Deploying bundle visualizer..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/visualizer-v2-13f9a3c35855b2f3a0f01d971c6b62012e5fe6f17da5f5e8d1d54a33ead7a300.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 waiting to be installed
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 installed
Bundle loaded.
Bundle run request sent.
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 waiting to reach expected scale 1
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 has scale 0, expected 1.
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
ConductR has been started:
  core: 1 instance
  agent: 3 instances
Check current bundle status with:
  conduct info
ID       NAME        #REP  #STR  #RUN
c4acb21  eslite         1     0     1
13f9a3c  visualizer     1     0     1
```

Similarly for Docker-based sandbox the number of containers is increased to 3.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ sandbox run 1.1.12 -f visualization
|------------------------------------------------|
| Stopping HAProxy                               |
|------------------------------------------------|
sandbox-haproxy
HAProxy has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Starting container cond-0 exposing 127.0.0.1:9999..
dd68a86804b09606531bf99c6d7d044b979a8502c945af39562705b72aa9c90a
Starting container cond-1 exposing 127.0.0.1:9909..
4fe03a3ce2ab2a0a07c5d63778a04b38cffdc3b10518501861f73bfea1a0b748
Starting container cond-2 exposing 127.0.0.1:9919..
0882d3c77f197e2e38cefda848ec50175728638ff629a833b48a3efca1cf3936
Waiting for ConductR to start.....
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
ConductR has been started
Check resource consumption of Docker containers that run the ConductR nodes with:
  docker stats cond-0 cond-1 cond-2
Check current bundle status with:
  conduct info

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct info
ID       NAME        #REP  #STR  #RUN
3f93d1f  visualizer     3     0     1
```

**Comment by fsat** [comment]
[Update lb.com with the new getting started.](https://trello.com/c/dxiIycli/481-update-lb-com-with-the-new-getting-started)

**Review by edwardcallahan — APPROVED** [review]

**Review by huntc — CHANGES_REQUESTED** [review]
I don't think that the default should be 3. I think it is fine for getting started that we explicitly set 3, but for regular development, 3 isn't necessary.

**Comment by fsat** [comment]
Closing this - we still have 1 as default.

**Pull request closed without merging**
