### PR TITLE
Conduct Info and Conduct ACLs improvements

### PR DESCRIPTION
**Pull request by fsat**
- Conduct Info: display Compatibility Version and Roles
- Conduct ACLs: remove System, System Version, and Endpoint Name

### CODE REVIEW

**Comment by fsat** [comment]
**Manual Test: Docker based sandbox**

Start the docker based sandbox

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 1.1-SNAPSHOT -f visualization
|------------------------------------------------|
| Stopping HAProxy                               |
|------------------------------------------------|
sandbox-haproxy
HAProxy has been successfully stopped
|------------------------------------------------|
| Stopping ConductR                              |
|------------------------------------------------|
ConductR core pid 3017 stopped
ConductR agent pid 3119 stopped
ConductR has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Starting container cond-0 exposing 127.0.0.1:9999..
9a42e7ee7447b0494e6734518e392958e6929ec17c875a500600d5550bf4d105
Waiting for ConductR to start...
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
ConductR has been started
Check resource consumption of Docker container that run the ConductR node with:
  docker stats cond-0
Check current bundle status with:
  conduct info
```

The `conduct info` now displays Compatible Version on `VER` column, and roles on `ROLES` column.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct info
ID       NAME         VER  #REP  #STR  #RUN  ROLES
90b6082  visualizer  v1.1     1     0     1  web
55436ba  eslite        v1     1     0     1  elasticsearch
```

`conduct acls` command still works. There's nothing to display since it's ConductR 1.1.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct acls http
METHOD  PATH  REWRITE  BUNDLE ID  BUNDLE NAME  STATUS

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct acls tcp
TCP/PORT  BUNDLE ID  BUNDLE NAME  STATUS
```

`conduct service-names` works.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct service-names
SERVICE NAME    BUNDLE ID  BUNDLE NAME  STATUS
elastic-search  55436ba    eslite       Running
```

**Comment by fsat** [comment]
**Manual Test: ConductR 2.0 based sandbox**

Start the sandbox.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.0.2 -f visualization
|------------------------------------------------|
| Stopping ConductR                              |
|------------------------------------------------|
cond-0
ConductR has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Starting ConductR agent instance on 192.168.10.1..
Waiting for ConductR to start.
|------------------------------------------------|
| Starting proxying feature                      |
|------------------------------------------------|
|------------------------------------------------|
| Starting HAProxy                               |
|------------------------------------------------|
Exposing the following ports [80, 443, 3000, 5601, 8999, 9000, 9200, 9999]
0d30c6d8645d3c37a62d31239fb1fd770fed60a8dd150c3a18ddcfda284e903f
Deploying bundle conductr-haproxy with configuration conductr-haproxy-dev-mode
Retrieving bundle..
Loading bundle from cache typesafe/bundle/conductr-haproxy
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/conductr-haproxy-v2-bdfa43d7ade7456af30a95e9ef4bce863d3029dc58b6824f5783881297d1983b.zip
Retrieving configuration..
Loading bundle configuration from cache typesafe/bundle-configuration/conductr-haproxy-dev-mode
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/configuration/conductr-haproxy-dev-mode-v2-e5f35046d59c27f4cfeebcc026f3e3b76e027b15223a8961b59d728e559402e2.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 is installed
Bundle loaded.
Bundle run request sent.
Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 waiting to reach expected scale 1
Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 has scale 0, expected 1..
Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 expected scale 1 is met
HAProxy has been started
Your Bundles are by default accessible on:
  192.168.10.1:9000
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/eslite-v1-3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 3349b6bfbc09e8d88123fee5b33b2717 is installed
Bundle loaded.
Bundle run request sent.
Bundle 3349b6bfbc09e8d88123fee5b33b2717 waiting to reach expected scale 1
Bundle 3349b6bfbc09e8d88123fee5b33b2717 has scale 0, expected 1.
Bundle 3349b6bfbc09e8d88123fee5b33b2717 expected scale 1 is met
|------------------------------------------------|
| Starting visualization feature                 |
|------------------------------------------------|
Deploying bundle visualizer..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/visualizer-v2-73595ecbdad1f01a05db5304046b4ad5c0a98ef83e201e507a153cea21087078.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 73595ecbdad1f01a05db5304046b4ad5 is installed
Bundle loaded.
Bundle run request sent.
Bundle 73595ecbdad1f01a05db5304046b4ad5 waiting to reach expected scale 1
Bundle 73595ecbdad1f01a05db5304046b4ad5 has scale 0, expected 1.
Bundle 73595ecbdad1f01a05db5304046b4ad5 expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
|- - - - - - - - - - - - - - - - - - - - - - - - |
| ConductR                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
ConductR has been started:
  core instance on 192.168.10.1
  agent instance on 192.168.10.1
ConductR service locator has been started on:
  192.168.10.1:9008
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Features                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
The following feature related bundles have been started:
  visualizer on 192.168.10.1:9999
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Bundles                                        |
|- - - - - - - - - - - - - - - - - - - - - - - - |
Check latest bundle status with:
  conduct info
Current bundle status:
ID               NAME              VER  #REP  #STR  #RUN  ROLES
bdfa43d-e5f3504  conductr-haproxy   v2     1     0     1  haproxy
3349b6b          eslite             v1     1     0     1  elasticsearch
73595ec          visualizer         v2     1     0     1  web
```

The `conduct info` now displays Compatible Version on `VER` column, and roles on `ROLES` column.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct info
ID               NAME              VER  #REP  #STR  #RUN  ROLES
bdfa43d-e5f3504  conductr-haproxy   v2     1     0     1  haproxy
3349b6b          eslite             v1     1     0     1  elasticsearch
73595ec          visualizer         v2     1     0     1  web
```

`conduct acls` command works as expected - there's nothing to display for TCP port.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct acls tcp
TCP/PORT  BUNDLE ID  BUNDLE NAME  STATUS

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct acls http
METHOD  PATH  REWRITE  BUNDLE ID  BUNDLE NAME  STATUS
*       ^/             73595ec    visualizer   Running
```

`conduct service-names` works.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct service-names
SERVICE NAME    BUNDLE ID  BUNDLE NAME  STATUS
elastic-search  3349b6b    eslite       Running
visualizer      73595ec    visualizer   Running
```

**Comment by fsat** [comment]
**Manual Test: ConductR 2.1 based sandbox**

Start the sandbox.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.1.0-SNAPSHOT -f visualization
|------------------------------------------------|
| Stopping HAProxy                               |
|------------------------------------------------|
sandbox-haproxy
HAProxy has been successfully stopped
|------------------------------------------------|
| Stopping ConductR                              |
|------------------------------------------------|
ConductR core pid 5334 stopped
ConductR agent pid 5434 stopped
ConductR has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Starting ConductR agent instance on 192.168.10.1..
Waiting for ConductR to start.
|------------------------------------------------|
| Starting proxying feature                      |
|------------------------------------------------|
|------------------------------------------------|
| Starting HAProxy                               |
|------------------------------------------------|
Exposing the following ports [80, 443, 3000, 5601, 8999, 9000, 9200, 9999]
c9d5ff7fbabae41e13f203872f421f358a145f38dfcf4158f880ad09de8ed714
Deploying bundle conductr-haproxy with configuration conductr-haproxy-dev-mode
Retrieving bundle..
Loading bundle from cache typesafe/bundle/conductr-haproxy
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/conductr-haproxy-v2-bdfa43d7ade7456af30a95e9ef4bce863d3029dc58b6824f5783881297d1983b.zip
Retrieving configuration..
Loading bundle configuration from cache typesafe/bundle-configuration/conductr-haproxy-dev-mode
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/configuration/conductr-haproxy-dev-mode-v2-e5f35046d59c27f4cfeebcc026f3e3b76e027b15223a8961b59d728e559402e2.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 is installed
Bundle loaded.
Bundle run request sent.
Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 waiting to reach expected scale 1
Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 has scale 0, expected 1..
Bundle bdfa43d7ade7456af30a95e9ef4bce86-e5f35046d59c27f4cfeebcc026f3e3b7 expected scale 1 is met
HAProxy has been started
Your Bundles are by default accessible on:
  192.168.10.1:9000
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/eslite-v1-3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 3349b6bfbc09e8d88123fee5b33b2717 is installed
Bundle loaded.
Bundle run request sent.
Bundle 3349b6bfbc09e8d88123fee5b33b2717 waiting to reach expected scale 1
Bundle 3349b6bfbc09e8d88123fee5b33b2717 has scale 0, expected 1.
Bundle 3349b6bfbc09e8d88123fee5b33b2717 expected scale 1 is met
|------------------------------------------------|
| Starting visualization feature                 |
|------------------------------------------------|
Deploying bundle visualizer..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/visualizer-v2-73595ecbdad1f01a05db5304046b4ad5c0a98ef83e201e507a153cea21087078.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 73595ecbdad1f01a05db5304046b4ad5 is installed
Bundle loaded.
Bundle run request sent.
Bundle 73595ecbdad1f01a05db5304046b4ad5 waiting to reach expected scale 1
Bundle 73595ecbdad1f01a05db5304046b4ad5 has scale 0, expected 1.
Bundle 73595ecbdad1f01a05db5304046b4ad5 expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
|- - - - - - - - - - - - - - - - - - - - - - - - |
| ConductR                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
ConductR has been started:
  core instance on 192.168.10.1
  agent instance on 192.168.10.1
ConductR service locator has been started on:
  192.168.10.1:9008
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Features                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
The following feature related bundles have been started:
  visualizer on 192.168.10.1:9999
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Bundles                                        |
|- - - - - - - - - - - - - - - - - - - - - - - - |
Check latest bundle status with:
  conduct info
Current bundle status:
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 3
ConductR Version(s): 0.1.0, 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID               NAME              VER  #REP  #STR  #RUN  ROLES
bdfa43d-e5f3504  conductr-haproxy   v2     1     0     1  haproxy
3349b6b          eslite             v1     1     0     1  elasticsearch
73595ec          visualizer         v2     1     0     1  web
```

The `conduct info` now displays Compatible Version on `VER` column, and roles on `ROLES` column.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct info
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 3
ConductR Version(s): 0.1.0, 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID               NAME              VER  #REP  #STR  #RUN  ROLES
bdfa43d-e5f3504  conductr-haproxy   v2     1     0     1  haproxy
3349b6b          eslite             v1     1     0     1  elasticsearch
73595ec          visualizer         v2     1     0     1  web
```

`conduct acls` command works as expected - there's nothing to display for TCP port.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct acls http
METHOD  PATH  REWRITE  BUNDLE ID  BUNDLE NAME  STATUS
*       ^/             73595ec    visualizer   Running

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct acls tcp
TCP/PORT  BUNDLE ID  BUNDLE NAME  STATUS
```

`conduct service-names` works.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct service-names
SERVICE NAME    BUNDLE ID  BUNDLE NAME  STATUS
elastic-search  3349b6b    eslite       Running
visualizer      73595ec    visualizer   Running
```

**Review by huntc — APPROVED** [review]

**Comment by fsat** [comment]
[CLI: Improve conduct info command](https://trello.com/c/8lHYN0AA/582-cli-improve-conduct-info-command)

**Pull request merged**
