### PR TITLE
Validate for supported JVM version when starting JVM based sandbox

### PR DESCRIPTION
**Pull request by fsat**
Only supports Oracle JDK version 1.8 and above.

### CODE REVIEW

**Comment by fsat** [comment]
Marked as wip for now - have manual tested the happy path, but not yet the validation error.

**Comment by fsat** [comment]
Manual test is completed successfully.

**Setup**

Install jenv from http://www.jenv.be/ to manage various versions of Java.

Install JDK 7 by downloading the `.dmg` from Oracle and register it with jenv.

```
Felixs-MBP-2:~ felixsatyaputra$ jenv add /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/
oracle64-1.7.0.80 added
1.7.0.80 added
1.7 added
```

**Manual test: supported java version**

Sandbox starts successfully with the supported java version.

Set java to supported version.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ jenv global 1.8

Felixs-MBP-2:conductr-cli felixsatyaputra$ jenv versions
  system
  1.7
  1.7.0.80
* 1.8 (set by /Users/felixsatyaputra/.jenv/version)
  1.8.0.72
  oracle64-1.7.0.80
  oracle64-1.8.0.72

Felixs-MBP-2:conductr-cli felixsatyaputra$ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
```

Sandbox is started successfully.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.0.0-rc.2
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Staring core 0 on 192.168.10.1..
Staring agent 0 on 192.168.10.1..
Waiting for ConductR to start..
|------------------------------------------------|
| Starting HAProxy                               |
|------------------------------------------------|
Deploying bundle conductr-haproxy with configuration conductr-haproxy-dev-mode
Retrieving bundle..
Loading bundle from cache typesafe/bundle/conductr-haproxy
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/conductr-haproxy-v2-fb0ea639d5e485a23b62f7affa88277099f7a1e236ebb5503b923ba97d68cd92.zip
Retrieving configuration..
Loading bundle configuration from cache typesafe/bundle-configuration/conductr-haproxy-dev-mode
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/conductr-haproxy-dev-mode-v2-d86c4eb272a4d75d86156983b23fde8b149393395c2dab0e8ea24ba862702691.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle fb0ea639d5e485a23b62f7affa882770-d86c4eb272a4d75d86156983b23fde8b waiting to be installed
Bundle fb0ea639d5e485a23b62f7affa882770-d86c4eb272a4d75d86156983b23fde8b installed
Bundle loaded.
Bundle run request sent.
Bundle fb0ea639d5e485a23b62f7affa882770-d86c4eb272a4d75d86156983b23fde8b waiting to reach expected scale 1
Bundle fb0ea639d5e485a23b62f7affa882770-d86c4eb272a4d75d86156983b23fde8b has scale 0, expected 1..
Bundle fb0ea639d5e485a23b62f7affa882770-d86c4eb272a4d75d86156983b23fde8b expected scale 1 is met
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/eslite-v1-e26c4de60b683daf9537d4e50533df6c5fe81e7082f727cc0de9778b3d15bede.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle e26c4de60b683daf9537d4e50533df6c waiting to be installed
Bundle e26c4de60b683daf9537d4e50533df6c installed
Bundle loaded.
Bundle run request sent.
Bundle e26c4de60b683daf9537d4e50533df6c waiting to reach expected scale 1
Bundle e26c4de60b683daf9537d4e50533df6c has scale 0, expected 1.
Bundle e26c4de60b683daf9537d4e50533df6c expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
ConductR has been started:
  core: 1 instance
  agent: 1 instance
Check current bundle status with:
  conduct info
ID               NAME              #REP  #STR  #RUN
fb0ea63-d86c4eb  conductr-haproxy     1     0     1
e26c4de          eslite               1     0     1
```

**Manual test: unsupported java version**

Sandbox doesn't start when unsupported java version is being used.

Set java to unsupported version.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ jenv global 1.7

Felixs-MBP-2:conductr-cli felixsatyaputra$ jenv versions
  system
* 1.7 (set by /Users/felixsatyaputra/.jenv/version)
  1.7.0.80
  1.8
  1.8.0.72
  oracle64-1.7.0.80
  oracle64-1.8.0.72

Felixs-MBP-2:conductr-cli felixsatyaputra$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

Sandbox doesn't start, error message is displayed.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.0.0-rc.2
Error: Unsupported JVM version: 1.7.0_80
Error: Please ensure Oracle JVM 1.8 and above is installed.
```

**Comment by fsat** [comment]
Manual test completed with expected result for both supported java and unsupported java version.

**Comment by fsat** [comment]
[ConductR CLI - new sandbox: perform jvm validation as part of sandbox run](https://trello.com/c/KmiLhPgd/459-conductr-cli-new-sandbox-perform-jvm-validation-as-part-of-sandbox-run)

**Review by markusjura — APPROVED** [review]

**Pull request merged**
