### PR TITLE
User Friendly Exception Handling Behaviour

### PR DESCRIPTION
**Pull request by fsat**
The purpose of the PR are:
- Prevent stacktrace to be displayed when operation is cancelled with `Ctrl+C`
- When internal error occurs, display a user-friendly error message instead of stacktrace, and save the stacktrace into a separate log file.

Required changes are:
- All the main functionality are moved into its own modules. This means `conduct.py`, `sandbox.py`, and `shazar.py` now has its own equivalent `conduct_main.py`, `sandbox_main.py`, and `shazar_main.py` respectively.
- The main files - `conduct.py`, `sandbox.py`, and `shazar.py` - are responsible for loading and running its respective main module.
- The main files are responsible for handling exceptions that may be raised by the main module, i.e. display friendly error message and log stacktrace into the file
- With this setup, the main files are able to wrap the loading and execution of the main module within a `try/except` block.
- This means exception encountered when loading the module will still have a friendly treatment. This is difficult to achieve without moving the main functionality into its own module.
- The main files has a special treatment for `Ctrl+C` (i.e.`KeyboardInterrupt`) and system exit (i.e. `SystemExit`)
- The functionality of this exception handling are consolidated in `main_handler.py` module which is used by the main files.

### CODE REVIEW

**Comment by huntc** [comment]
Hard to see what has changed here - wholes appear to have changed. I'll trust you though. ;-)

LGTM

**Comment by fsat** [comment]
Oh, there's still more things to be done - I've only got the keyboard interrupt handled. I've still got to figure out the way to setup logging so only exceptions goes into file.

**Comment by fsat** [comment]
Also the changes you've seen is basically me moving the content of main methods into separate module. The reasoning behind this is so that I can trap possible exceptions in the body of the main file (i.e. possible bug assigning constant from env variable for example)

**Comment by fsat** [comment]
Various manual tests has been done on this PR. I'll post these as separate comments due to the length of the comment.

I have also ran the unit tests on Win7, Python 3.5 - all passed.

**Comment by fsat** [comment]
**Manual Test: Cancelling operation with Ctrl+C no longer dumps a stacktrace on the console**

For this test, I have placed a sleep within the CLI so I have a chance to cancel the operation.

```
192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct logs vis
^C192-168-1-5:conductr-cli felixsatyaputra$
```

**Comment by fsat** [comment]
**Manual Test: Exception is displayed in a more friendly manner**

For this test, I purposely break something within the CLI which will raise an exception.

```
192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct logs self-induced/error
Error: Encountered unexpected error.
Error: Reason: KeyError 'timestamp'
Error: Further information of the error can be found in the error log file: /Users/felixsatyaputra/.conductr/errors.log
```

Users then can inspect the actual stack trace in the error log displayed above.

The log file is managed through Python's rolling file appender, which is configured roll over at 3MB with 1 backup file.

I have also logged the command and its argument into the log file which will hopefully be useful for troubleshooting purposes.

```
192-168-1-5:conductr-cli felixsatyaputra$ cat /Users/felixsatyaputra/.conductr/errors.log
2016-03-18 12:00:06,728: Failure running the following command: ['/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/conduct.py', 'logs', 'self-induced/error']
Traceback (most recent call last):
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/main_handler.py", line 8, in run
    result = callback()
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/conduct.py", line 6, in main_method
    conduct_main.run()
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/conduct_main.py", line 290, in run
    is_completed_without_error = args.func(args)
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/validation.py", line 40, in handler
    return func(*args, **kwargs)
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/validation.py", line 56, in handler
    return func(*args, **kwargs)
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/conduct_logs.py", line 24, in logs
    } for event in json.loads(response.text)
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/conduct_logs.py", line 24, in <listcomp>
    } for event in json.loads(response.text)
KeyError: 'timestamp'
```

**Comment by fsat** [comment]
**Manual Test: Sandbox commands**

Sandbox commands work as expected.

```
192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.sandbox init
Docker VM default already installed
Docker VM default already running
Docker VM default already has sufficient RAM and CPU
Sandbox initialization complete

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.sandbox stop
Stopping ConductR..
cond-0

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.sandbox run 0.1.0 -f logging -f visualization
Starting ConductR nodes..
Starting container cond-0 exposing 192.168.99.100:9200, 192.168.99.100:5601, 192.168.99.100:9999..
2515b17498fe560a1b082ed76c48c035601726719591ba2c045bc9beb4b4d478

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct info
ID       NAME                    #REP  #STR  #RUN
21d3b3e  conductr-elasticsearch     1     0     1
a448850  conductr-kibana            1     0     1
c2c8fe4  visualizer                 1     0     1
```

**Comment by fsat** [comment]
**Manual Test: Conduct commands**

Conduct commands work as expected.

```
192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct info
ID       NAME                    #REP  #STR  #RUN
21d3b3e  conductr-elasticsearch     1     0     1
a448850  conductr-kibana            1     0     1
c2c8fe4  visualizer                 1     0     1

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct stop vis
Bundle stop request sent.
Bundle c2c8fe41612ab20eb5ad8274d767201c waiting to reach expected scale 0
Bundle c2c8fe41612ab20eb5ad8274d767201c expected scale 0 is met
Unload bundle with: conduct unload --ip 192.168.99.100 c2c8fe4
Print ConductR info with: conduct info --ip 192.168.99.100

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct info
ID       NAME                    #REP  #STR  #RUN
21d3b3e  conductr-elasticsearch     1     0     1
a448850  conductr-kibana            1     0     1
c2c8fe4  visualizer                 1     0     0

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct unload vis
Bundle unload request sent.
Bundle c2c8fe41612ab20eb5ad8274d767201c waiting to be uninstalled
Bundle c2c8fe41612ab20eb5ad8274d767201c uninstalled
Print ConductR info with: conduct info --ip 192.168.99.100

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct info
ID       NAME                    #REP  #STR  #RUN
21d3b3e  conductr-elasticsearch     1     0     1
a448850  conductr-kibana            1     0     1

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct load ~/workspace/typesafe-fsat/conductr/visualizer/target/bundle/visualizer-v1.1-c2c8fe41612ab20eb5ad8274d767201c36fcf4681d4cd88f78f5455a1c9be67d.zip
Retrieving bundle...
Bintray credentials loaded from /Users/felixsatyaputra/.bintray/.credentials
Retrieving file:///Users/felixsatyaputra/workspace/typesafe-fsat/conductr/visualizer/target/bundle/visualizer-v1.1-c2c8fe41612ab20eb5ad8274d767201c36fcf4681d4cd88f78f5455a1c9be67d.zip
Loading bundle to ConductR...
Bundle c2c8fe41612ab20eb5ad8274d767201c waiting to be installed
Bundle c2c8fe41612ab20eb5ad8274d767201c installed
Bundle loaded.
Start bundle with: conduct run --ip 192.168.99.100 c2c8fe4
Unload bundle with: conduct unload --ip 192.168.99.100 c2c8fe4
Print ConductR info with: conduct info --ip 192.168.99.100

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct info
ID       NAME                    #REP  #STR  #RUN
21d3b3e  conductr-elasticsearch     1     0     1
a448850  conductr-kibana            1     0     1
c2c8fe4  visualizer                 1     0     0

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct run vis
Bundle run request sent.
Bundle c2c8fe41612ab20eb5ad8274d767201c waiting to reach expected scale 1
Bundle c2c8fe41612ab20eb5ad8274d767201c has scale 0, expected 1
Bundle c2c8fe41612ab20eb5ad8274d767201c expected scale 1 is met
Stop bundle with: conduct stop --ip 192.168.99.100 c2c8fe4
Print ConductR info with: conduct info --ip 192.168.99.100

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct info
ID       NAME                    #REP  #STR  #RUN
21d3b3e  conductr-elasticsearch     1     0     1
a448850  conductr-kibana            1     0     1
c2c8fe4  visualizer                 1     0     1

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct services
SERVICE                      BUNDLE ID  BUNDLE NAME             STATUS
http://127.0.0.1:9200        21d3b3e    conductr-elasticsearch  Running
http://:5601                 a448850    conductr-kibana         Running
http://:9200/elastic-search  21d3b3e    conductr-elasticsearch  Running
http://:9999                 c2c8fe4    visualizer              Running
tcp://:9300                  21d3b3e    conductr-elasticsearch  Running

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct events vis
TIME      EVENT                                         DESC
11:38:44  conductr.scaleScheduler.scaleRescheduled      Scale rescheduled: requestId=8df48b31-e9fd-4648-9895-ad1b165e9771, bundleId=c2c8fe41612ab20eb5ad8274d767201c
11:39:16  conductr.loadScheduler.unloadBundleRequested  Unload bundle requested: requestId=3caf1c1b-0567-4191-89a6-398ffb75e0aa, bundleId=c2c8fe41612ab20eb5ad8274d767201c
11:39:16  conductr.loadExecutor.bundleRemoved           Bundle removed: bundleId=c2c8fe41612ab20eb5ad8274d767201c, uniqueAddress=UniqueAddress(akka.tcp://conductr@172.17.0.2:9004,1702469316)
11:40:05  conductr.loadExecutor.bundleWritten           Bundle written: requestId=044bc7eb-7a04-49d4-9556-d22d2503aa26, bundleName=visualizer, bundleId=c2c8fe41612ab20eb5ad8274d767201c
11:40:26  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: requestId=2b0bc2d8-961b-4e46-a955-e3f2ab4fc676, bundleId=c2c8fe41612ab20eb5ad8274d767201c, scale=1
11:40:26  conductr.scaleScheduler.scaleRescheduled      Scale rescheduled: requestId=d30b3c45-d526-42a8-995c-76b2e05ec601, bundleId=c2c8fe41612ab20eb5ad8274d767201c
11:40:26  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: requestId=d30b3c45-d526-42a8-995c-76b2e05ec601, bundleId=c2c8fe41612ab20eb5ad8274d767201c, scale=1
11:40:26  conductr.launcher.bundleStarted               Bundle started: bundleId=c2c8fe41612ab20eb5ad8274d767201c, host=172.17.0.2
11:40:28  conductr.scaleScheduler.scaleRescheduled      Scale rescheduled: requestId=3959b687-18aa-4fc9-8a18-1d61ef70177f, bundleId=c2c8fe41612ab20eb5ad8274d767201c
11:40:28  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: requestId=3959b687-18aa-4fc9-8a18-1d61ef70177f, bundleId=c2c8fe41612ab20eb5ad8274d767201c, scale=1

192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.conduct logs vis
TIME      HOST          LOG
11:35:46  2515b17498fe  [info] application - Signalled start to ConductR
11:35:46  2515b17498fe  [WARN] [03/18/2016 00:35:46.521] [main] [ActorConfiguration$] Configuration does not define any actors to monitor
11:35:46  2515b17498fe  [info] play.api.Play - Application started (Prod)
11:35:46  2515b17498fe  [info] p.c.s.NettyServer - Listening for HTTP on /172.17.0.2:10609
11:40:28  2515b17498fe  [info] application - Signalled start to ConductR
11:40:28  2515b17498fe  [WARN] [03/18/2016 00:40:28.331] [main] [ActorConfiguration$] Configuration does not define any actors to monitor
11:40:28  2515b17498fe  [info] play.api.Play - Application started (Prod)
11:40:28  2515b17498fe  [info] p.c.s.NettyServer - Listening for HTTP on /172.17.0.2:10609
```

**Comment by fsat** [comment]
**Manual Test: Shazar command**

Shazar commands work as expected.

```
192-168-1-5:conductr-cli felixsatyaputra$ python3 -m conductr_cli.shazar ~/tmp/shazar-test/
Created digested ZIP archive at ./shazar-test-29558338dd34376ec91aa5f5efa9890fb311b7c6963f003c26aefe34c7937442.zip

192-168-1-5:conductr-cli felixsatyaputra$ unzip -l shazar-test-29558338dd34376ec91aa5f5efa9890fb311b7c6963f003c26aefe34c7937442.zip
Archive:  shazar-test-29558338dd34376ec91aa5f5efa9890fb311b7c6963f003c26aefe34c7937442.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
       10  03-18-16 11:50   shazar-test/test.txt
 --------                   -------
       10                   1 file
```

**Comment by huntc** [comment]
I like the new shazar output!

All looks quite awesome. Ship it!

**Pull request merged**
