### PR TITLE
Conduct Info: Inspecting bundle now displays execution for bundles without endpoint

### PR DESCRIPTION
**Pull request by fsat**

### CODE REVIEW

**Comment by fsat** [comment]
Fixes #392

**Comment by fsat** [comment]
Marked as wip - manual test pending

**Comment by fsat** [comment]
**Manual test: ConductR 2.1**

Manual test is done successfully.

**Setup**

ConductR master branch is deployed into local sandbox and started with the following command.

```
sandbox run 0.1.0
```

Test bundle without endpoint is created for the purpose of test. `shazar` is used to package the bundle.

```
192-168-1-5:typesafe-fsat felixsatyaputra$ find bundle-no-endpoints -type f
bundle-no-endpoints/bundle.conf
bundle-no-endpoints/one/start-one

192-168-1-5:typesafe-fsat felixsatyaputra$ cat bundle-no-endpoints/bundle.conf
version                  = "1"
name                     = "bundle-no-endpoint"
system                   = "bundle-no-endpoint"
systemVersion            = "0.1.0"
compatibilityVersion     = "1"
tags                     = ["tag"]
nrOfCpus                 = 1.0
memory                   = 8000000
diskSpace                = 10000000
roles                    = ["test"]
components               = {
  "one" = {
    description      = "A script that echos forever"
    file-system-type = "universal"
    start-command    = ["one/start-one"]
    endpoints        = {
    }
  }
}

192-168-1-5:typesafe-fsat felixsatyaputra$ cat bundle-no-endpoints/one/start-one
#!/usr/bin/env bash

curl -X PUT -v "${CONDUCTR_STATUS}/bundles/${BUNDLE_ID}?isStarted=true"

while true; do
  echo test
  sleep 1
done
```

Test bundle is then deployed and run on the sandbox.

The state of the bundles is described below.

```
192-168-1-5:conductr-cli felixsatyaputra$ conduct info -v
[
  {
    "attributes": {
      "bundleName": "eslite",
      "compatibilityVersion": "1",
      "diskSpace": 200000000,
      "memory": 402653184,
      "nrOfCpus": 0.1,
      "roles": [
        "elasticsearch"
      ],
      "system": "eslite",
      "systemVersion": "1",
      "tags": []
    },
    "bundleConfig": {
      "endpoints": {
        "akka-remote": {
          "bindProtocol": "tcp"
        },
        "es": {
          "bindProtocol": "http",
          "serviceName": "elastic-search"
        }
      }
    },
    "bundleDigest": "3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5",
    "bundleExecutions": [
      {
        "endpoints": {
          "akka-remote": {
            "bindPort": 10822,
            "hostPort": 10822
          },
          "es": {
            "bindPort": 10007,
            "hostPort": 10007
          }
        },
        "host": "192.168.10.1",
        "isActive": true,
        "isStarted": true,
        "pid": 53518,
        "startTime": "2017-04-05T03:16:48.861Z"
      }
    ],
    "bundleId": "3349b6bfbc09e8d88123fee5b33b2717",
    "bundleInstallations": [
      {
        "bundleFile": "file:///Users/felixsatyaputra/.conductr/images/tmp/conductr/192.168.10.1/bundles/3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip",
        "uniqueAddress": {
          "address": "akka.tcp://conductr@192.168.10.1:9004",
          "uid": 479428973
        }
      }
    ],
    "bundleScale": {
      "nrOfReschedules": 0,
      "scale": 1
    },
    "hasError": false
  },
  {
    "attributes": {
      "bundleName": "bundle-no-endpoint",
      "compatibilityVersion": "1",
      "diskSpace": 10000000,
      "memory": 8000000,
      "nrOfCpus": 1,
      "roles": [
        "test"
      ],
      "system": "bundle-no-endpoint",
      "systemVersion": "0.1.0",
      "tags": [
        "tag"
      ]
    },
    "bundleConfig": {
      "endpoints": {}
    },
    "bundleDigest": "7f5874760a2a949d1860d4185ab70437c51094821a2e8c229d2ee7e3e8279edf",
    "bundleExecutions": [
      {
        "endpoints": {},
        "host": "192.168.10.1",
        "isActive": true,
        "isStarted": true,
        "pid": 53684,
        "startTime": "2017-04-05T03:17:15.961Z"
      }
    ],
    "bundleId": "7f5874760a2a949d1860d4185ab70437",
    "bundleInstallations": [
      {
        "bundleFile": "file:///Users/felixsatyaputra/.conductr/images/tmp/conductr/192.168.10.1/bundles/7f5874760a2a949d1860d4185ab70437c51094821a2e8c229d2ee7e3e8279edf.zip",
        "uniqueAddress": {
          "address": "akka.tcp://conductr@192.168.10.1:9004",
          "uid": 479428973
        }
      }
    ],
    "bundleScale": {
      "nrOfReschedules": 0,
      "scale": 1
    },
    "hasError": false
  }
]
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 10
ConductR Version(s): 0.1.0, 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID       NAME                TAG  #REP  #STR  #RUN  ROLES
3349b6b  eslite                      1     0     1  elasticsearch
7f58747  bundle-no-endpoint  tag     1     0     1  test
```

**Inspecting bundle without endpoint**

The `PID` is shown in the bundle execution as expected.

```
192-168-1-5:typesafe-fsat felixsatyaputra$ conduct info bundle-no-endpoint
BUNDLE ATTRIBUTES
-----------------
Bundle Id              7f58747
Bundle Name            bundle-no-endpoint
Compatibility Version  1
System                 bundle-no-endpoint
System Version         0.1.0
Tags                   tag
Nr of CPUs             1
Memory                 8000000
Disk Space             10000000
Roles                  test
Bundle Digest          7f5874760a2a949d1860d4185ab70437c51094821a2e8c229d2ee7e3e8279edf
Error                  No

BUNDLE SCALE
------------
Nr of Reschedules  0
Scale              1

BUNDLE INSTALLATIONS
--------------------
Host    192.168.10.1
Bundle  /Users/felixsatyaputra/.conductr/images/tmp/conductr/192.168.10.1/bundles/7f5874760a2a949d1860d4185ab70437c51094821a2e8c229d2ee7e3e8279edf.zip

BUNDLE EXECUTIONS
-----------------
HOST            PID  STARTED    UPTIME
192.168.10.1  53684      Yes  22m, 50s

```

**Inspecting bundle with endpoint**

The bundle execution is displayed as-is.

```
192-168-1-5:typesafe-fsat felixsatyaputra$ conduct info eslite
BUNDLE ATTRIBUTES
-----------------
Bundle Id              3349b6b
Bundle Name            eslite
Compatibility Version  1
System                 eslite
System Version         1
Tags
Nr of CPUs             0.1
Memory                 402653184
Disk Space             200000000
Roles                  elasticsearch
Bundle Digest          3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5
Error                  No

BUNDLE SCALE
------------
Nr of Reschedules  0
Scale              1

BUNDLE INSTALLATIONS
--------------------
Host    192.168.10.1
Bundle  /Users/felixsatyaputra/.conductr/images/tmp/conductr/192.168.10.1/bundles/3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip

BUNDLE EXECUTIONS
-----------------
ENDPOINT     HOST            PID  STARTED    UPTIME  BIND_PORT  HOST_PORT
akka-remote  192.168.10.1  53518      Yes  22m, 30s      10822      10822
es           192.168.10.1  53518      Yes  22m, 30s      10007      10007

SERVICE NAMES
-------------
SERVICE NAME    STATUS
elastic-search  Running

```

**Comment by fsat** [comment]
**Manual test: ConductR 2.0**

Manual test is done successfully.

**Setup**

Sandbox is started with ConductR 2.0

```
sandbox run 2.0.5
```

Same test bundle from previous comment is deployed and started.

The state of the sandbox is as following.

```
192-168-1-5:conductr-cli felixsatyaputra$ conduct info -v
[
  {
    "attributes": {
      "bundleName": "eslite",
      "compatibilityVersion": "1",
      "diskSpace": 200000000,
      "memory": 402653184,
      "nrOfCpus": 0.1,
      "roles": [
        "elasticsearch"
      ],
      "system": "eslite",
      "systemVersion": "1"
    },
    "bundleConfig": {
      "endpoints": {
        "akka-remote": {
          "bindProtocol": "tcp"
        },
        "es": {
          "bindProtocol": "http",
          "serviceName": "elastic-search"
        }
      }
    },
    "bundleDigest": "3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5",
    "bundleExecutions": [
      {
        "endpoints": {
          "akka-remote": {
            "bindPort": 10822,
            "hostPort": 10822
          },
          "es": {
            "bindPort": 10007,
            "hostPort": 10007
          }
        },
        "host": "192.168.10.1",
        "isStarted": true
      }
    ],
    "bundleId": "3349b6bfbc09e8d88123fee5b33b2717",
    "bundleInstallations": [
      {
        "bundleFile": "file:///Users/felixsatyaputra/.conductr/images/tmp/conductr/192.168.10.1/bundles/3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip",
        "uniqueAddress": {
          "address": "akka.tcp://conductr@192.168.10.1:9004",
          "uid": 37412720
        }
      }
    ],
    "bundleScale": {
      "nrOfReschedules": 0,
      "scale": 1
    },
    "hasError": false
  },
  {
    "attributes": {
      "bundleName": "bundle-no-endpoint",
      "compatibilityVersion": "1",
      "diskSpace": 10000000,
      "memory": 8000000,
      "nrOfCpus": 1,
      "roles": [
        "test"
      ],
      "system": "bundle-no-endpoint",
      "systemVersion": "0.1.0"
    },
    "bundleDigest": "7f5874760a2a949d1860d4185ab70437c51094821a2e8c229d2ee7e3e8279edf",
    "bundleExecutions": [],
    "bundleId": "7f5874760a2a949d1860d4185ab70437",
    "bundleInstallations": [
      {
        "bundleFile": "file:///Users/felixsatyaputra/.conductr/images/tmp/conductr/192.168.10.1/bundles/7f5874760a2a949d1860d4185ab70437c51094821a2e8c229d2ee7e3e8279edf.zip",
        "uniqueAddress": {
          "address": "akka.tcp://conductr@192.168.10.1:9004",
          "uid": 37412720
        }
      }
    ],
    "hasError": false
  }
]
ID       NAME                VER  #REP  #STR  #RUN  ROLES
3349b6b  eslite               v1     1     0     1  elasticsearch
7f58747  bundle-no-endpoint   v1     1     0     0  test
```

**Bundle without Endpoint**

Bundle execution is displayed as expected, `PID` is displayed as `Unknown` as it's not available from the Bundle endpoint.

```
192-168-1-5:conductr-cli felixsatyaputra$ conduct info bundle-no-endpoint
BUNDLE ATTRIBUTES
-----------------
Bundle Id              7f58747
Bundle Name            bundle-no-endpoint
Compatibility Version  1
System                 bundle-no-endpoint
System Version         0.1.0
Nr of CPUs             1
Memory                 8000000
Disk Space             10000000
Roles                  test
Bundle Digest          7f5874760a2a949d1860d4185ab70437c51094821a2e8c229d2ee7e3e8279edf
Error                  No

BUNDLE INSTALLATIONS
--------------------
Host    192.168.10.1
Bundle  /Users/felixsatyaputra/.conductr/images/tmp/conductr/192.168.10.1/bundles/7f5874760a2a949d1860d4185ab70437c51094821a2e8c229d2ee7e3e8279edf.zip

```

**Bundle with Endpoint**

Bundle execution is displayed as expected, `PID` is displayed as `Unknown` as it's not available from the Bundle endpoint.

```
192-168-1-5:conductr-cli felixsatyaputra$ conduct info eslite
BUNDLE ATTRIBUTES
-----------------
Bundle Id              3349b6b
Bundle Name            eslite
Compatibility Version  1
System                 eslite
System Version         1
Nr of CPUs             0.1
Memory                 402653184
Disk Space             200000000
Roles                  elasticsearch
Bundle Digest          3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5
Error                  No

BUNDLE SCALE
------------
Nr of Reschedules  0
Scale              1

BUNDLE INSTALLATIONS
--------------------
Host    192.168.10.1
Bundle  /Users/felixsatyaputra/.conductr/images/tmp/conductr/192.168.10.1/bundles/3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip

BUNDLE EXECUTIONS
-----------------
ENDPOINT     HOST              PID  STARTED   UPTIME  BIND_PORT  HOST_PORT
akka-remote  192.168.10.1  Unknown      Yes  Unknown      10822      10822
es           192.168.10.1  Unknown      Yes  Unknown      10007      10007

SERVICE NAMES
-------------
SERVICE NAME    STATUS
elastic-search  Running
```

**Review by huntc — APPROVED** [review]

**Comment by fsat** [comment]
**Manual test: ConductR 1.1**

The command `conduct info` still works as expected with ConductR 1.1.

```
192-168-1-5:conductr-cli felixsatyaputra$ sandbox run 1.1.2 -f visualization
|------------------------------------------------|
| Stopping ConductR                              |
|------------------------------------------------|
cond-0
ConductR has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Starting container cond-0 exposing 127.0.0.1:9999..
ab689f4eca94871627acdb0386239349590e341e413b437546e842df5cdb5f7f
Waiting for ConductR to start..
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
ConductR has been started
Check resource consumption of Docker container that run the ConductR node with:
  docker stats cond-0
Check current bundle status with:
  conduct info

192-168-1-5:conductr-cli felixsatyaputra$ conduct info -v
[
  {
    "attributes": {
      "bundleName": "visualizer",
      "compatibilityVersion": "1.1",
      "diskSpace": 35000000,
      "memory": 67108864,
      "nrOfCpus": 1,
      "roles": [
        "web"
      ],
      "system": "visualizer",
      "systemVersion": "1.1"
    },
    "bundleDigest": "0a1abfa781bd879b8947d101f586b2c8e8c0b1efe3b4e77cf2c6a01d4b27c71f",
    "bundleExecutions": [],
    "bundleId": "0a1abfa781bd879b8947d101f586b2c8",
    "bundleInstallations": [
      {
        "bundleFile": "file:///tmp/0a1abfa781bd879b8947d101f586b2c8e8c0b1efe3b4e77cf2c6a01d4b27c71f.zip",
        "uniqueAddress": {
          "address": "akka.tcp://conductr@172.17.0.2:9004",
          "uid": -1696571266
        }
      }
    ],
    "hasError": false
  }
]
ID       NAME         VER  #REP  #STR  #RUN  ROLES
0a1abfa  visualizer  v1.1     1     0     0  web
192-168-1-5:conductr-cli felixsatyaputra$ conduct info -v
[
  {
    "attributes": {
      "bundleName": "visualizer",
      "compatibilityVersion": "1.1",
      "diskSpace": 35000000,
      "memory": 67108864,
      "nrOfCpus": 1,
      "roles": [
        "web"
      ],
      "system": "visualizer",
      "systemVersion": "1.1"
    },
    "bundleConfig": {
      "endpoints": {
        "web": {
          "bindProtocol": "http",
          "services": [
            "http://:9999"
          ]
        }
      }
    },
    "bundleDigest": "0a1abfa781bd879b8947d101f586b2c8e8c0b1efe3b4e77cf2c6a01d4b27c71f",
    "bundleExecutions": [
      {
        "endpoints": {
          "web": {
            "bindPort": 10822,
            "hostPort": 10822
          }
        },
        "host": "172.17.0.2",
        "isStarted": true
      }
    ],
    "bundleId": "0a1abfa781bd879b8947d101f586b2c8",
    "bundleInstallations": [
      {
        "bundleFile": "file:///tmp/0a1abfa781bd879b8947d101f586b2c8e8c0b1efe3b4e77cf2c6a01d4b27c71f.zip",
        "uniqueAddress": {
          "address": "akka.tcp://conductr@172.17.0.2:9004",
          "uid": -1696571266
        }
      }
    ],
    "bundleScale": {
      "scale": 1
    },
    "hasError": false
  }
]
ID       NAME         VER  #REP  #STR  #RUN  ROLES
0a1abfa  visualizer  v1.1     1     0     1  web

192-168-1-5:conductr-cli felixsatyaputra$ conduct info vis
BUNDLE ATTRIBUTES
-----------------
Bundle Id              0a1abfa
Bundle Name            visualizer
Compatibility Version  1.1
System                 visualizer
System Version         1.1
Nr of CPUs             1
Memory                 67108864
Disk Space             35000000
Roles                  web
Bundle Digest          0a1abfa781bd879b8947d101f586b2c8e8c0b1efe3b4e77cf2c6a01d4b27c71f
Error                  No

BUNDLE SCALE
------------
Scale  1

BUNDLE INSTALLATIONS
--------------------
Host    172.17.0.2
Bundle  /tmp/0a1abfa781bd879b8947d101f586b2c8e8c0b1efe3b4e77cf2c6a01d4b27c71f.zip

BUNDLE EXECUTIONS
-----------------
ENDPOINT  HOST            PID  STARTED   UPTIME  BIND_PORT  HOST_PORT
web       172.17.0.2  Unknown      Yes  Unknown      10822      10822
```

**Pull request merged**
