### PR TITLE
Implement `--env` flag for `bndl` and allow `conduct load` to respect `bndl` arguments

### PR DESCRIPTION
**Pull request by longshorej**
- [x] Implementation
- [x] Manual Tests
- [x] More Manual Tests
- [x] New Unit Tests

### CODE REVIEW

**Comment by longshorej** [comment]
[Support environment vars for bndl](https://trello.com/c/WZlT8GBR/646-support-environment-vars-for-bndl)

**Comment by longshorej** [comment]
This net-effect of these two changes is that it enables usage such as: `conduct load nginx --env SOME_VAR=some_value`.

**Review by huntc — APPROVED** [review]
I'm liking it

**Comment by longshorej** [comment]
### Manual Test

This test has a manually prepared bundle that starts a webserver that responds to requests with the value of the env variable `MESSAGE`. We test to make sure the `--env` flag is honored and alters this response.

**Showing bundle setup**
```bash
$ ls -lah bundle
total 16K
drwxr-xr-x 3 longshorej longshorej 4.0K May 11 16:42 .
drwxr-xr-x 3 longshorej longshorej 4.0K May 11 16:42 ..
-rw-r--r-- 1 longshorej longshorej  663 May 11 16:46 bundle.conf
drwxr-xr-x 2 longshorej longshorej 4.0K May 11 16:41 server
-> 0

$ cat bundle/bundle.conf 
version               = "1"
name                  = "env-test"
compatibility-version = "1"
tags                  = []
system                = "env-test"
system-version        = "1"
nr-of-cpus            = 0.1
memory                = 134217728
disk-space            = 10485760
roles                 = []
annotations           = {}
components = {
  "server" = {
    description      = ""
    file-system-type = "universal"
    start-command    = ["server/server.py"]
    endpoints        = {}
  }
  "bundle-status" = {
    description      = ""
    file-system-type = "universal"
    start-command    = ["check", "file:///bin/true"]
    endpoints        = {}
  }
}
-> 0

$ cat bundle/server/server.py 
#!/usr/bin/env python3

from http.server import BaseHTTPRequestHandler, HTTPServer
import os

class testHTTPServer_RequestHandler(BaseHTTPRequestHandler):
  def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type','text/html')
        self.end_headers()
        message = os.getenv('MESSAGE')
        if message is None:
            message = 'missing env MESSAGE'
        self.wfile.write(bytes(message, 'UTF-8'))
        return

server_address = ('127.0.0.1', 9000)
httpd = HTTPServer(server_address, testHTTPServer_RequestHandler)
httpd.serve_forever()
-> 0
```

**Running without `--env flag` shows the default message defined in `server.py`**
```bash
$ conduct load bundle
Retrieving bundle..
Loading bundle to ConductR..
[#################################################] 100%
Bundle 2cb8715f2f6994cdbfe850d94b446627 is installed
Bundle loaded.
Start bundle with:        conduct run 2cb8715
Unload bundle with:       conduct unload 2cb8715
Print ConductR info with: conduct info
Print bundle info with:   conduct info 2cb8715
-> 0

$ conduct run 2cb8715
Bundle run request sent.
Bundle 2cb8715f2f6994cdbfe850d94b446627 waiting to reach expected scale 1
Bundle 2cb8715f2f6994cdbfe850d94b446627 has scale 0, expected 1..
Bundle 2cb8715f2f6994cdbfe850d94b446627 expected scale 1 is met
Stop bundle with:         conduct stop 2cb8715
Print ConductR info with: conduct info
Print bundle info with:   conduct info 2cb8715
-> 0

$ curl http://127.0.0.1:9000
missing env MESSAGE-> 0

$ conduct stop 2cb8715
Bundle stop request sent.
Bundle 2cb8715f2f6994cdbfe850d94b446627 waiting to reach expected scale 0
Bundle 2cb8715f2f6994cdbfe850d94b446627 expected scale 0 is met
Unload bundle with:       conduct unload 2cb8715
Print ConductR info with: conduct info
Print bundle info with:   conduct info 2cb8715
-> 0
```

**Providing a `--env` flag changes the behavior of the application**
```bash
$ conduct load bundle --env 'MESSAGE=hello world!'
Retrieving bundle..
Loading bundle to ConductR..
[#################################################] 100%
Bundle 2cb8715f2f6994cdbfe850d94b446627-b4871002da8bd15b1b10982f40f34e9d is installed
Bundle loaded.
Start bundle with:        conduct run 2cb8715-b487100
Unload bundle with:       conduct unload 2cb8715-b487100
Print ConductR info with: conduct info
Print bundle info with:   conduct info 2cb8715-b487100
-> 0

$ conduct run 2cb8715-b487100
Bundle run request sent.
Bundle 2cb8715f2f6994cdbfe850d94b446627-b4871002da8bd15b1b10982f40f34e9d waiting to reach expected scale 1
Bundle 2cb8715f2f6994cdbfe850d94b446627-b4871002da8bd15b1b10982f40f34e9d has scale 0, expected 1.
Bundle 2cb8715f2f6994cdbfe850d94b446627-b4871002da8bd15b1b10982f40f34e9d expected scale 1 is met
Stop bundle with:         conduct stop 2cb8715-b487100
Print ConductR info with: conduct info
Print bundle info with:   conduct info 2cb8715-b487100
-> 0

$ curl http://127.0.0.1:9000
hello world!-> 0

$ conduct stop 2cb8715-b487100
Bundle stop request sent.
Bundle 2cb8715f2f6994cdbfe850d94b446627-b4871002da8bd15b1b10982f40f34e9d waiting to reach expected scale 0
Bundle 2cb8715f2f6994cdbfe850d94b446627-b4871002da8bd15b1b10982f40f34e9d has scale 1, expected 0
Bundle 2cb8715f2f6994cdbfe850d94b446627-b4871002da8bd15b1b10982f40f34e9d expected scale 0 is met
Unload bundle with:       conduct unload 2cb8715-b487100
Print ConductR info with: conduct info
Print bundle info with:   conduct info 2cb8715-b487100
-> 0
```

**Pull request merged**
