### PR TITLE
Conduct run commands exits when encountering bundle error

### PR DESCRIPTION
**Pull request by fsat**
Also display bundle events and logs upon encountering error

### CODE REVIEW

**Comment by fsat** [comment]
Fixes #316

**Comment by fsat** [comment]
Marked as wip - some unit test still missing + manual test not yet done

**Comment by fsat** [comment]
**Manual Test: Help text**

The help text for `conduct run` is as following. The additional argument options required for invoking `conduct_events.events()` and `conduct_logs.logs()` (i.e. `--lines`, `--utc`, and `--follow`) is hidden from the help text.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct run --help
usage: conduct run [-h] [--scale SCALE] [--affinity AFFINITY]
                   [--scheme SCHEME] [--host HOST] [-i IP] [-p PORT]
                   [--base-path BASE_PATH] [-v] [--disable-instructions] [-q]
                   [--long-ids] [--api-version {1,2}]
                   [--settings-dir CLI_SETTINGS_DIR]
                   [--custom-settings-file CUSTOM_SETTINGS_FILE]
                   [--custom-plugins-dir CUSTOM_PLUGINS_DIR]
                   [--wait-timeout WAIT_TIMEOUT] [--no-wait]
                   bundle

positional arguments:
  bundle                The ID of the bundle

optional arguments:
  -h, --help            show this help message and exit
  --scale SCALE         The optional number of executions
                        Defaults to 1
  --affinity AFFINITY   The optional ID of the bundle to run alongside with (v2.0 onwards)
  --scheme SCHEME       The optional ConductR scheme, defaults to http
  --host HOST           The optional ConductR host
                        Defaults to one of the value in this order:
                        1. $CONDUCTR_HOST
                        2. $CONDUCTR_IP
                        3. IP address of the docker VM or
                        4. 127.0.0.1
  -i IP, --ip IP        The optional ConductR IP
                        Defaults to one of the value in this order:
                        1. $CONDUCTR_IP
                        2. IP address of the docker VM
                        3. 127.0.0.1
  -p PORT, --port PORT  The optional ConductR port
                        Defaults to $CONDUCTR_PORT or 9005
  --base-path BASE_PATH
                        The optional ConductR base path
                        Defaults to $DEFAULT_BASE_PATH or /
  -v, --verbose         Print detailed information of the command
  --disable-instructions
                        Disables further instruction output after the command has been succeeded
                        Defaults to False
  -q                    Prints affected bundle id on screen if enabled
                        Defaults to False
  --long-ids            Print long Bundle IDs
  --api-version {1,2}   Sets which ConductR api version to be used
                        Defaults to 2
  --settings-dir CLI_SETTINGS_DIR
                        Directory where ConductR CLI settings are stored
                        Defaults to /Users/felixsatyaputra/.conductr
  --custom-settings-file CUSTOM_SETTINGS_FILE
                        Configuration where custom settings for ConductR CLI are stored in HOCON format
                        Defaults to /Users/felixsatyaputra/.conductr/settings.conf
  --custom-plugins-dir CUSTOM_PLUGINS_DIR
                        Directory where custom plugins for ConductR CLI are stored
                        Defaults to /Users/felixsatyaputra/.conductr/plugins
  --wait-timeout WAIT_TIMEOUT
                        Timeout in seconds waiting for bundle scale to be achieved in conduct run
                        or bundle to be stopped in conduct stop
                        Defaults to 60
  --no-wait             Disables waiting for bundle scale to be achieved in conduct run
                        or bundle to be stopped in conduct stop
                        Defaults to False
```

**Comment by fsat** [comment]
**Manual Test: Bundle failing to start**

The following test bundle is created. The test bundle will exit with a non-zero exit code, thus indicating failure.

```
Felixs-MBP-2:test-failing-bundle felixsatyaputra$ find test-failing-bundle
test-failing-bundle
test-failing-bundle/bundle.conf
test-failing-bundle/one
test-failing-bundle/one/start-one

Felixs-MBP-2:test-failing-bundle felixsatyaputra$ cat test-failing-bundle/bundle.conf
version                  = "1"
name                     = "failing-bundle"
system                   = "failing-bundle"
systemVersion            = "0.1.0"
compatibilityVersion     = "1"
nrOfCpus                 = 0.1
memory                   = 8000000
diskSpace                = 10000000
roles                    = ["test"]
components               = {
  "one" = {
    description      = "A script that echos 5 times, and exits with code 1"
    file-system-type = "universal"
    start-command    = ["one/start-one"]
    endpoints        = {
    }
  }
}

Felixs-MBP-2:test-failing-bundle felixsatyaputra$ cat test-failing-bundle/one/start-one
#!/usr/bin/env bash

# for i in $(seq 1 200); do
#   echo one-$i
#   sleep 10
# done

echo "Going to sleep for 10 seconds"
sleep 10
echo "Bailing out"
exit 1
```

When the bundle is loaded and run on a running sandbox, the command terminates upon encountering bundle error. Bundle events and logs are displayed as part of the output.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load ~/workspace/sandbox/test-failing-bundle/test-failing-bundle-62da2a20e24faf10677ce62d11d72ff263eea94a7badd5ca1895d020d781e634.zip
Retrieving bundle..
Loading bundle to ConductR..
[#################################################] 100%
Bundle 62da2a20e24faf10677ce62d11d72ff2 is installed
Bundle loaded.
Start bundle with:        conduct run 62da2a2
Unload bundle with:       conduct unload 62da2a2
Print ConductR info with: conduct info
Print bundle info with:   conduct info 62da2a2

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct info
Licensed To: 45967794-07cf-4162-baea-515918988c44
Max ConductR agents: 3
Expires In: 65 days (Thu 20 Jul 2017 20:42PM)
ConductR Version(s): 2.0.*, 2.1.0-alpha.1
Grants: akka-sbr, cinnamon, conductr

ID       NAME            TAG  #REP  #STR  #RUN  ROLES
7dc78f8  eslite                  1     0     1  elasticsearch
62da2a2  failing-bundle          1     0     0  test

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct run 62da2a2
Bundle run request sent.
Bundle 62da2a20e24faf10677ce62d11d72ff2 waiting to reach expected scale 1
Bundle 62da2a20e24faf10677ce62d11d72ff2 has scale 0, expected 1..
Error: Failure to scale bundle 62da2a20e24faf10677ce62d11d72ff2

Check latest bundle events with:
  conduct events 62da2a20e24faf10677ce62d11d72ff2
Current bundle events:
TIME                          EVENT                                         DESC
Tue 2017-05-16T10:50:49+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T10:50:51+1000  conductr.launcher.bundleExited                Bundle exited: host=192.168.10.1, exitValue=143 - rescheduling its execution
Tue 2017-05-16T10:50:52+1000  conductr.scaleScheduler.scaleRescheduled      Scale of 1 rescheduled
Tue 2017-05-16T10:50:52+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T10:50:52+1000  conductr.launcher.bundleStarted               Bundle started: host=192.168.10.1
Tue 2017-05-16T10:51:02+1000  conductr.launcher.bundleExited                Bundle exited: host=192.168.10.1, exitValue=143 - rescheduling its execution
Tue 2017-05-16T10:51:02+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T10:51:02+1000  conductr.scaleScheduler.scaleRescheduled      Scale of 1 rescheduled
Tue 2017-05-16T10:51:02+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T10:51:02+1000  conductr.launcher.bundleStarted               Bundle started: host=192.168.10.1

Check latest bundle logs with:
  conduct logs 62da2a20e24faf10677ce62d11d72ff2
Current bundle logs:
TIME                          HOST          LOG
Tue 2017-05-16T10:50:41+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T10:50:41+1000  Felixs-MBP-2  Going to sleep for 10 seconds
Tue 2017-05-16T10:50:51+1000  Felixs-MBP-2  Bailing out
Tue 2017-05-16T10:50:51+1000  Felixs-MBP-2  Component one exited with 1
Tue 2017-05-16T10:50:51+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T10:50:52+1000  Felixs-MBP-2  Going to sleep for 10 seconds
Tue 2017-05-16T10:51:02+1000  Felixs-MBP-2  Bailing out
Tue 2017-05-16T10:51:02+1000  Felixs-MBP-2  Component one exited with 1
Tue 2017-05-16T10:51:02+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T10:51:02+1000  Felixs-MBP-2  Going to sleep for 10 seconds

Error: Bundle 62da2a20e24faf10677ce62d11d72ff2 has error
```

**Comment by fsat** [comment]
**Manual Test: Bundle failing to start + Consolidated Logging Unavailable**

The following test bundle is created. The test bundle will exit with a non-zero exit code, thus indicating failure.

```
Felixs-MBP-2:test-failing-bundle felixsatyaputra$ find test-failing-bundle
test-failing-bundle
test-failing-bundle/bundle.conf
test-failing-bundle/one
test-failing-bundle/one/start-one

Felixs-MBP-2:test-failing-bundle felixsatyaputra$ cat test-failing-bundle/bundle.conf
version                  = "1"
name                     = "failing-bundle"
system                   = "failing-bundle"
systemVersion            = "0.1.0"
compatibilityVersion     = "1"
nrOfCpus                 = 0.1
memory                   = 8000000
diskSpace                = 10000000
roles                    = ["test"]
components               = {
  "one" = {
    description      = "A script that echos 5 times, and exits with code 1"
    file-system-type = "universal"
    start-command    = ["one/start-one"]
    endpoints        = {
    }
  }
}

Felixs-MBP-2:test-failing-bundle felixsatyaputra$ cat test-failing-bundle/one/start-one
#!/usr/bin/env bash

# for i in $(seq 1 200); do
#   echo one-$i
#   sleep 10
# done

echo "Going to sleep for 10 seconds"
sleep 10
echo "Bailing out"
exit 1
```

Run the sandbox without ESLite:

```
sandbox run 2.1.0-alpha.1 --no-default-features
```

When the bundle is loaded and run on a running sandbox, the command terminates upon encountering bundle error. Warning message about enabling consolidated logging is displayed.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load ~/workspace/sandbox/test-failing-bundle/test-failing-bundle-62da2a20e24faf10677ce62d11d72ff263eea94a7badd5ca1895d020d781e634.zip
Retrieving bundle..
Loading bundle to ConductR..
[#################################################] 100%
Bundle 62da2a20e24faf10677ce62d11d72ff2 is installed
Bundle loaded.
Start bundle with:        conduct run 62da2a2
Unload bundle with:       conduct unload 62da2a2
Print ConductR info with: conduct info
Print bundle info with:   conduct info 62da2a2

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct info
Licensed To: 45967794-07cf-4162-baea-515918988c44
Max ConductR agents: 3
Expires In: 64 days (Thu 20 Jul 2017 20:42PM)
ConductR Version(s): 2.0.*, 2.1.0-alpha.1
Grants: akka-sbr, cinnamon, conductr

ID       NAME            TAG  #REP  #STR  #RUN  ROLES
62da2a2  failing-bundle          1     0     0  test

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct run 62da2a2
Bundle run request sent.
Bundle 62da2a20e24faf10677ce62d11d72ff2 waiting to reach expected scale 1
Bundle 62da2a20e24faf10677ce62d11d72ff2 has scale 0, expected 1..
Error: Failure to scale bundle 62da2a20e24faf10677ce62d11d72ff2

Warning: Please enable consolidated logging to view bundle events and logs

Check latest bundle events with:
  conduct events 62da2a20e24faf10677ce62d11d72ff2

Check latest bundle logs with:
  conduct logs 62da2a20e24faf10677ce62d11d72ff2

Error: Bundle 62da2a20e24faf10677ce62d11d72ff2 has error
```

**Review by huntc — APPROVED** [review]
I like it!

Re.:

```
Error: Bundle 62da2a20e24faf10677ce62d11d72ff2 has error
```

... I think it'd be great to direct the user to `conduct events 62da2a20e24faf10677ce62d11d72ff2`. WDYT?

**Comment by fsat** [comment]
@huntc - We did display the message indicating the use of `conduct events` and `conduct logs` - perhaps it's buried in the middle message:

```Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load ~/workspace/sandbox/test-failing-bundle/test-failing-bundle-62da2a20e24faf10677ce62d11d72ff263eea94a7badd5ca1895d020d781e634.zip
Retrieving bundle..
Loading bundle to ConductR..
[#################################################] 100%
Bundle 62da2a20e24faf10677ce62d11d72ff2 is installed
Bundle loaded.
Start bundle with:        conduct run 62da2a2
Unload bundle with:       conduct unload 62da2a2
Print ConductR info with: conduct info
Print bundle info with:   conduct info 62da2a2

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct info
Licensed To: 45967794-07cf-4162-baea-515918988c44
Max ConductR agents: 3
Expires In: 65 days (Thu 20 Jul 2017 20:42PM)
ConductR Version(s): 2.0.*, 2.1.0-alpha.1
Grants: akka-sbr, cinnamon, conductr

ID       NAME            TAG  #REP  #STR  #RUN  ROLES
7dc78f8  eslite                  1     0     1  elasticsearch
62da2a2  failing-bundle          1     0     0  test

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct run 62da2a2
Bundle run request sent.
Bundle 62da2a20e24faf10677ce62d11d72ff2 waiting to reach expected scale 1
Bundle 62da2a20e24faf10677ce62d11d72ff2 has scale 0, expected 1..
Error: Failure to scale bundle 62da2a20e24faf10677ce62d11d72ff2

Check latest bundle events with:
  conduct events 62da2a20e24faf10677ce62d11d72ff2
Current bundle events:
TIME                          EVENT                                         DESC
Tue 2017-05-16T10:50:49+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T10:50:51+1000  conductr.launcher.bundleExited                Bundle exited: host=192.168.10.1, exitValue=143 - rescheduling its execution
Tue 2017-05-16T10:50:52+1000  conductr.scaleScheduler.scaleRescheduled      Scale of 1 rescheduled
Tue 2017-05-16T10:50:52+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T10:50:52+1000  conductr.launcher.bundleStarted               Bundle started: host=192.168.10.1
Tue 2017-05-16T10:51:02+1000  conductr.launcher.bundleExited                Bundle exited: host=192.168.10.1, exitValue=143 - rescheduling its execution
Tue 2017-05-16T10:51:02+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T10:51:02+1000  conductr.scaleScheduler.scaleRescheduled      Scale of 1 rescheduled
Tue 2017-05-16T10:51:02+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T10:51:02+1000  conductr.launcher.bundleStarted               Bundle started: host=192.168.10.1

Check latest bundle logs with:
  conduct logs 62da2a20e24faf10677ce62d11d72ff2
Current bundle logs:
TIME                          HOST          LOG
Tue 2017-05-16T10:50:41+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T10:50:41+1000  Felixs-MBP-2  Going to sleep for 10 seconds
Tue 2017-05-16T10:50:51+1000  Felixs-MBP-2  Bailing out
Tue 2017-05-16T10:50:51+1000  Felixs-MBP-2  Component one exited with 1
Tue 2017-05-16T10:50:51+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T10:50:52+1000  Felixs-MBP-2  Going to sleep for 10 seconds
Tue 2017-05-16T10:51:02+1000  Felixs-MBP-2  Bailing out
Tue 2017-05-16T10:51:02+1000  Felixs-MBP-2  Component one exited with 1
Tue 2017-05-16T10:51:02+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T10:51:02+1000  Felixs-MBP-2  Going to sleep for 10 seconds

Error: Bundle 62da2a20e24faf10677ce62d11d72ff2 has error
```

So repeat the message about `conduct events` and `conduct logs` after the last line, i.e.

```
Error: Bundle 62da2a20e24faf10677ce62d11d72ff2 has error

Inspect the latest bundle events and logs using:
  conduct events 62da2a20e24faf10677ce62d11d72ff2
  conduct logs 62da2a20e24faf10677ce62d11d72ff2
```

Wdyt?

**Comment by huntc** [comment]
Ok cool. Thanks.

**Comment by fsat** [comment]
Updated message to display `conduct events` and `conduct logs` command at the end of the output.

When consolidated logging is available:

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct run 62da2a2
Bundle run request sent.
Bundle 62da2a20e24faf10677ce62d11d72ff2 waiting to reach expected scale 1
Bundle 62da2a20e24faf10677ce62d11d72ff2 has scale 0, expected 1
Error: Failure to scale bundle 62da2a20e24faf10677ce62d11d72ff2

Check latest bundle events with:
  conduct events 62da2a20e24faf10677ce62d11d72ff2
Current bundle events:
TIME                          EVENT                                         DESC
Tue 2017-05-16T13:11:44+1000  conductr.scaleScheduler.scaleRescheduled      Scale of 1 rescheduled
Tue 2017-05-16T13:11:44+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T13:11:44+1000  conductr.launcher.bundleStarted               Bundle started: host=192.168.10.1
Tue 2017-05-16T13:11:54+1000  conductr.launcher.bundleExited                Bundle exited: host=192.168.10.1, exitValue=143 - rescheduling its execution
Tue 2017-05-16T13:11:55+1000  conductr.scaleScheduler.scaleRescheduled      Scale of 1 rescheduled
Tue 2017-05-16T13:11:55+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T13:11:55+1000  conductr.launcher.bundleStarted               Bundle started: host=192.168.10.1
Tue 2017-05-16T13:11:56+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
Tue 2017-05-16T13:11:56+1000  conductr.scaleScheduler.scaleRescheduled      Scale of 1 rescheduled
Tue 2017-05-16T13:11:56+1000  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1

Check latest bundle logs with:
  conduct logs 62da2a20e24faf10677ce62d11d72ff2
Current bundle logs:
TIME                          HOST          LOG
Tue 2017-05-16T13:11:33+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T13:11:34+1000  Felixs-MBP-2  Going to sleep for 10 seconds
Tue 2017-05-16T13:11:44+1000  Felixs-MBP-2  Bailing out
Tue 2017-05-16T13:11:44+1000  Felixs-MBP-2  Component one exited with 1
Tue 2017-05-16T13:11:44+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T13:11:44+1000  Felixs-MBP-2  Going to sleep for 10 seconds
Tue 2017-05-16T13:11:54+1000  Felixs-MBP-2  Bailing out
Tue 2017-05-16T13:11:54+1000  Felixs-MBP-2  Component one exited with 1
Tue 2017-05-16T13:11:54+1000  Felixs-MBP-2  Stopping bundle
Tue 2017-05-16T13:11:55+1000  Felixs-MBP-2  Going to sleep for 10 seconds

Error: Bundle 62da2a20e24faf10677ce62d11d72ff2 has error

Inspect the latest bundle events and logs using:
  conduct events 62da2a20e24faf10677ce62d11d72ff2
  conduct logs 62da2a20e24faf10677ce62d11d72ff2
```

When consolidated logging is not available:

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct run 62da2a2
Bundle run request sent.
Bundle 62da2a20e24faf10677ce62d11d72ff2 waiting to reach expected scale 1
Bundle 62da2a20e24faf10677ce62d11d72ff2 has scale 0, expected 1
Error: Failure to scale bundle 62da2a20e24faf10677ce62d11d72ff2
Error: Bundle 62da2a20e24faf10677ce62d11d72ff2 has error
Warning: Please enable consolidated logging to view bundle events and logs
Once enabled, inspect the latest bundle events and logs using:
  conduct events 62da2a20e24faf10677ce62d11d72ff2
  conduct logs 62da2a20e24faf10677ce62d11d72ff2
```

**Pull request merged**
