### PR TITLE
Enable Continuous Delivery as default feature

### PR DESCRIPTION
**Pull request by fsat**

### CODE REVIEW

**Comment by fsat** [comment]
Marked as wip - manual test pending.

**Comment by fsat** [comment]
Manual test is completed successfully.

CD is enabled as default feature.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.1.0-alpha.1
|------------------------------------------------|
| Stopping ConductR                              |
|------------------------------------------------|
ConductR core pid 91031 stopped
ConductR agent pid 91132 stopped
ConductR has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Waiting for ConductR to start..
Starting ConductR agent instance on 192.168.10.1..
|------------------------------------------------|
| OCI-in-Docker support unavailable.             |
|------------------------------------------------|
|------------------------------------------------|
| To provide support ensure Docker is running    |
| and restart the sandbox                        |
|------------------------------------------------|
|------------------------------------------------|
| Starting continuous delivery feature           |
|------------------------------------------------|
Deploying bundle continuous-delivery..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/continuous-delivery
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/continuous-delivery-2.1.0-870ee7d6a4f5853229275cca14b604b8aca62a5e74819c0a092858cc75b6c186.zip
Loading bundle to ConductR..
[##################################################] 100%
Bundle 870ee7d6a4f5853229275cca14b604b8 is installed
Bundle loaded.
Bundle run request sent.
Bundle 870ee7d6a4f5853229275cca14b604b8 waiting to reach expected scale 1
Bundle 870ee7d6a4f5853229275cca14b604b8 has scale 0, expected 1...
Bundle 870ee7d6a4f5853229275cca14b604b8 expected scale 1 is met
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/eslite-2.1.0-57e432d0c647be2bbc83fa8e59ee469bb59d1f72df31f3d82cab0ad396130fe7.zip
Loading bundle to ConductR..
[##################################################] 100%
Bundle 57e432d0c647be2bbc83fa8e59ee469b is installed
Bundle loaded.
Bundle run request sent.
Bundle 57e432d0c647be2bbc83fa8e59ee469b waiting to reach expected scale 1
Bundle 57e432d0c647be2bbc83fa8e59ee469b has scale 0, expected 1.
Bundle 57e432d0c647be2bbc83fa8e59ee469b expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
|- - - - - - - - - - - - - - - - - - - - - - - - |
| ConductR                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
ConductR has been started:
  core instance on 192.168.10.1
  agent instance on 192.168.10.1
ConductR service locator has been started on:
  192.168.10.1:9008
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Proxy                                          |
|- - - - - - - - - - - - - - - - - - - - - - - - |
HAProxy has not been started
To enable proxying ensure Docker is running and restart the sandbox
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Bundles                                        |
|- - - - - - - - - - - - - - - - - - - - - - - - |
Check latest bundle status with:
  conduct info
Current bundle status:
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 10
ConductR Version(s): 0.1.0, 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID       NAME                   TAG  #REP  #STR  #RUN  ROLES
870ee7d  continuous-delivery  2.1.0     1     0     1  continuous-delivery
57e432d  eslite               2.1.0     1     0     1  elasticsearch
Felixs-MBP-2:conductr-cli felixsatyaputra$
```

Also works with other feature flags.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.1.0-alpha.1 --feature visualization
|------------------------------------------------|
| Stopping ConductR                              |
|------------------------------------------------|
ConductR core pid 92404 stopped
ConductR agent pid 92505 stopped
ConductR has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Waiting for ConductR to start..
Starting ConductR agent instance on 192.168.10.1..
|------------------------------------------------|
| OCI-in-Docker support unavailable.             |
|------------------------------------------------|
|------------------------------------------------|
| To provide support ensure Docker is running    |
| and restart the sandbox                        |
|------------------------------------------------|
|------------------------------------------------|
| Starting continuous delivery feature           |
|------------------------------------------------|
Deploying bundle continuous-delivery..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/continuous-delivery
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/continuous-delivery-2.1.0-870ee7d6a4f5853229275cca14b604b8aca62a5e74819c0a092858cc75b6c186.zip
Loading bundle to ConductR..
[##################################################] 100%
Bundle 870ee7d6a4f5853229275cca14b604b8 is installed
Bundle loaded.
Bundle run request sent.
Bundle 870ee7d6a4f5853229275cca14b604b8 waiting to reach expected scale 1
Bundle 870ee7d6a4f5853229275cca14b604b8 has scale 0, expected 1...
Bundle 870ee7d6a4f5853229275cca14b604b8 expected scale 1 is met
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/eslite-2.1.0-57e432d0c647be2bbc83fa8e59ee469bb59d1f72df31f3d82cab0ad396130fe7.zip
Loading bundle to ConductR..
[##################################################] 100%
Bundle 57e432d0c647be2bbc83fa8e59ee469b is installed
Bundle loaded.
Bundle run request sent.
Bundle 57e432d0c647be2bbc83fa8e59ee469b waiting to reach expected scale 1
Bundle 57e432d0c647be2bbc83fa8e59ee469b has scale 0, expected 1.
Bundle 57e432d0c647be2bbc83fa8e59ee469b expected scale 1 is met
|------------------------------------------------|
| Starting visualization feature                 |
|------------------------------------------------|
Deploying bundle visualizer..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving file:///Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/visualizer
Resolving bundle typesafe/bundle/visualizer
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving https://dl.bintray.com/typesafe/bundle/typesafe/visualizer/2.1.0-31fe9536b5f3252cc7b432ab06bd9ba31b7258d920f7147020392a7058074606/visualizer-2.1.0-31fe9536b5f3252cc7b432ab06bd9ba31b7258d920f7147020392a7058074606.zip
[##################################################] 100%
Loading bundle to ConductR..
[##################################################] 100%
Bundle 31fe9536b5f3252cc7b432ab06bd9ba3 is installed
Bundle loaded.
Bundle run request sent.
Bundle 31fe9536b5f3252cc7b432ab06bd9ba3 waiting to reach expected scale 1
Bundle 31fe9536b5f3252cc7b432ab06bd9ba3 has scale 0, expected 1.
Bundle 31fe9536b5f3252cc7b432ab06bd9ba3 expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
|- - - - - - - - - - - - - - - - - - - - - - - - |
| ConductR                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
ConductR has been started:
  core instance on 192.168.10.1
  agent instance on 192.168.10.1
ConductR service locator has been started on:
  192.168.10.1:9008
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Proxy                                          |
|- - - - - - - - - - - - - - - - - - - - - - - - |
HAProxy has not been started
To enable proxying ensure Docker is running and restart the sandbox
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Features                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
The following feature related bundles have been started:
  visualizer on 192.168.10.1:9008/services/visualizer
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Bundles                                        |
|- - - - - - - - - - - - - - - - - - - - - - - - |
Check latest bundle status with:
  conduct info
Current bundle status:
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 10
ConductR Version(s): 0.1.0, 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID       NAME                   TAG  #REP  #STR  #RUN  ROLES
870ee7d  continuous-delivery  2.1.0     1     0     1  continuous-delivery
57e432d  eslite               2.1.0     1     0     1  elasticsearch
31fe953  visualizer           2.1.0     1     0     1  web
```

Also works if `-f continuous-delivery` is specified.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.1.0-alpha.1 --feature continuous-delivery
|------------------------------------------------|
| Stopping ConductR                              |
|------------------------------------------------|
ConductR core pid 92807 stopped
ConductR agent pid 92908 stopped
ConductR has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Waiting for ConductR to start..
Starting ConductR agent instance on 192.168.10.1..
|------------------------------------------------|
| OCI-in-Docker support unavailable.             |
|------------------------------------------------|
|------------------------------------------------|
| To provide support ensure Docker is running    |
| and restart the sandbox                        |
|------------------------------------------------|
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/eslite-2.1.0-57e432d0c647be2bbc83fa8e59ee469bb59d1f72df31f3d82cab0ad396130fe7.zip
Loading bundle to ConductR..
[##################################################] 100%
Bundle 57e432d0c647be2bbc83fa8e59ee469b is installed
Bundle loaded.
Bundle run request sent.
Bundle 57e432d0c647be2bbc83fa8e59ee469b waiting to reach expected scale 1
Bundle 57e432d0c647be2bbc83fa8e59ee469b has scale 0, expected 1...
Bundle 57e432d0c647be2bbc83fa8e59ee469b expected scale 1 is met
|------------------------------------------------|
| Starting continuous delivery feature           |
|------------------------------------------------|
Deploying bundle continuous-delivery..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/continuous-delivery
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/continuous-delivery-2.1.0-870ee7d6a4f5853229275cca14b604b8aca62a5e74819c0a092858cc75b6c186.zip
Loading bundle to ConductR..
[##################################################] 100%
Bundle 870ee7d6a4f5853229275cca14b604b8 is installed
Bundle loaded.
Bundle run request sent.
Bundle 870ee7d6a4f5853229275cca14b604b8 waiting to reach expected scale 1
Bundle 870ee7d6a4f5853229275cca14b604b8 has scale 0, expected 1.
Bundle 870ee7d6a4f5853229275cca14b604b8 expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
|- - - - - - - - - - - - - - - - - - - - - - - - |
| ConductR                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
ConductR has been started:
  core instance on 192.168.10.1
  agent instance on 192.168.10.1
ConductR service locator has been started on:
  192.168.10.1:9008
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Proxy                                          |
|- - - - - - - - - - - - - - - - - - - - - - - - |
HAProxy has not been started
To enable proxying ensure Docker is running and restart the sandbox
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Bundles                                        |
|- - - - - - - - - - - - - - - - - - - - - - - - |
Check latest bundle status with:
  conduct info
Current bundle status:
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 10
ConductR Version(s): 0.1.0, 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID       NAME                   TAG  #REP  #STR  #RUN  ROLES
57e432d  eslite               2.1.0     1     0     1  elasticsearch
870ee7d  continuous-delivery  2.1.0     1     0     1  continuous-delivery
```

Will be disabled if default features is disabled.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.1.0-alpha.1 --no-default-features
|------------------------------------------------|
| Stopping ConductR                              |
|------------------------------------------------|
ConductR core pid 93291 stopped
ConductR agent pid 93392 stopped
ConductR has been successfully stopped
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Waiting for ConductR to start..
Starting ConductR agent instance on 192.168.10.1..
|------------------------------------------------|
| OCI-in-Docker support unavailable.             |
|------------------------------------------------|
|------------------------------------------------|
| To provide support ensure Docker is running    |
| and restart the sandbox                        |
|------------------------------------------------|
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
|- - - - - - - - - - - - - - - - - - - - - - - - |
| ConductR                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
ConductR has been started:
  core instance on 192.168.10.1
  agent instance on 192.168.10.1
ConductR service locator has been started on:
  192.168.10.1:9008
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Proxy                                          |
|- - - - - - - - - - - - - - - - - - - - - - - - |
HAProxy has not been started
To enable proxying ensure Docker is running and restart the sandbox
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Bundles                                        |
|- - - - - - - - - - - - - - - - - - - - - - - - |
Check latest bundle status with:
  conduct info
Current bundle status:
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 10
ConductR Version(s): 0.1.0, 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID  NAME  TAG  #REP  #STR  #RUN  ROLES
```

**Comment by fsat** [comment]
[Enable CD as default CLI feature](https://trello.com/c/2gy3zool/812-enable-cd-as-default-cli-feature)

**Review by huntc — APPROVED** [review]
Is this back compatible to 2.0?

**Comment by fsat** [comment]
@huntc - yes the CD bundle is backward compatible with ConductR 2.0, the test result with ConductR 2.0 is here:

https://github.com/typesafehub/conductr/pull/1798#issuecomment-305700757

**Pull request merged**
