### PR TITLE
Drop Docker machine support

### PR DESCRIPTION
**Pull request by markusjura**
The conductr-cli sandbox command with the ConductR JVM approach will not support Windows anymore. Only for Windows 10 Home Edition and older Windows versions Docker machine is the recommended installation path on docker.com. Also, Docker for Mac is already out for more than 6 months.

Therefore, we going to drop Docker machine support. This also simplied the HAProxy implementation of the sandbox JVM approach, see https://github.com/typesafehub/conductr-cli/pull/245#issuecomment-273042918.

If the `DOCKER_MACHINE_NAME` environment variable is set then we throw now the following error when starting the sandbox:

```
$ sandbox run 1.1.12
Error: Docker machine envs are set but Docker machine is not supported by the conductr-cli.
Error: We recommend to use one of following the Docker distributions depending on your OS:
Error:   Linux:                                         Docker Engine
Error:   MacOS:                                         Docker for Mac
Error: For more information checkout: https://www.docker.com/products/overview
```

### CODE REVIEW

**Comment by huntc** [comment]
I'm presuming that the CLI remains available to be used from Windows, but what we mean here is that there will be no sandbox support...

**Review by fsat — APPROVED** [review]
@markusjura - PR lgtm, but I'd suggest a quick manual check for `conduct` commands to make sure:
* IP address resolution still works, especially when either `CONDUCTR_HOST`, `CONDUCTR_IP`, `--ip`, or `--host` is specified.
* It still works on Windows. I expect this to be the case since the `conduct` command doesn't have any direct dependencies to Docker machine.

**Comment by fsat** [comment]
[ConductR CLI: Drop docker-machine support](https://trello.com/c/zBFTDn1M/472-conductr-cli-drop-docker-machine-support)

**Comment by markusjura** [comment]
> I'm presuming that the CLI remains available to be used from Windows, but what we mean here is that there will be no sandbox support...

@huntc Yes, that is correct. Only the sandbox commands will not work on Windows anymore.

**Comment by markusjura** [comment]
## Manual tests

### MacOS

**conduct load --ip**

```
$ conduct load --ip 192.168.10.1 visualizer
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Retrieving from cache /Users/mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 4bbf7b78508b53645eb4dc7b769e2643 waiting to be installed
Bundle 4bbf7b78508b53645eb4dc7b769e2643 installed
Bundle loaded.
Start bundle with: conduct run 4bbf7b7
Unload bundle with: conduct unload 4bbf7b7
Print ConductR info with: conduct info
```

**conduct load --host**

```
$ conduct load --host 192.168.10.1 visualizer
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Retrieving from cache /Users/mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 4bbf7b78508b53645eb4dc7b769e2643 waiting to be installed
Bundle 4bbf7b78508b53645eb4dc7b769e2643 installed
Bundle loaded.
Start bundle with: conduct run 4bbf7b7
Unload bundle with: conduct unload 4bbf7b7
Print ConductR info with: conduct info
```

**CONDUCTR_HOST**

```
$ export CONDUCTR_HOST=192.168.10.1
mj@Markuss-MacBook-Pro:~/workspace$ conduct load visualizer
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Retrieving from cache /Users/mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 4bbf7b78508b53645eb4dc7b769e2643 waiting to be installed
Bundle 4bbf7b78508b53645eb4dc7b769e2643 installed
Bundle loaded.
Start bundle with: conduct run 4bbf7b7
Unload bundle with: conduct unload 4bbf7b7
Print ConductR info with: conduct info
```

**CONDUCTR_IP**

```
$ export CONDUCTR_IP=192.168.10.1
mj@Markuss-MacBook-Pro:~/workspace$ conduct load visualizer
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/mj/.lightbend/commercial.credentials
Retrieving from cache /Users/mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 4bbf7b78508b53645eb4dc7b769e2643 waiting to be installed
Bundle 4bbf7b78508b53645eb4dc7b769e2643 installed
Bundle loaded.
Start bundle with: conduct run 4bbf7b7
Unload bundle with: conduct unload 4bbf7b7
Print ConductR info with: conduct info
```

### Windows

**conduct load --ip**

```
python -m conductr_cli.conduct load --ip 10.10.10.10 visualizer
Retrieving bundle..
Cache directory C:\Users\mj/.conductr/cache has the permissions 777. Setting permissions to 700.
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from C:\Users\mj/.lightbend/commercial.credentials
Retrieving from cache C:\Users\mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
Error: Unable to contact ConductR.
Error: Reason: HTTPConnectionPool(host='10.10.10.10', port=9005): Max retries exceeded with url: /v2/bundles (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0431C850>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat',))
Error: Make sure it can be accessed at http://10.10.10.10:9005/v2/bundles
```

**conduct load --host**

```
python -m conductr_cli.conduct load --host 10.10.10.10 visualizer
Retrieving bundle..
Cache directory C:\Users\mj/.conductr/cache has the permissions 777. Setting permissions to 700.
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from C:\Users\mj/.lightbend/commercial.credentials
Retrieving from cache C:\Users\mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
Error: Unable to contact ConductR.
Error: Reason: HTTPConnectionPool(host='10.10.10.10', port=9005): Max retries exceeded with url: /v2/bundles (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x04B2C850>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat',))
Error: Make sure it can be accessed at http://10.10.10.10:9005/v2/bundles
```

**CONDUCTR_HOST**

```
>set CONDUCTR_IP=10.10.10.10
>python -m conductr_cli.conduct load visualizer
Retrieving bundle..
Cache directory C:\Users\mj/.conductr/cache has the permissions 777. Setting permissions to 700.
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from C:\Users\mj/.lightbend/commercial.credentials
Retrieving from cache C:\Users\mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
Error: Unable to contact ConductR.
Error: Reason: HTTPConnectionPool(host='10.10.10.10', port=9005): Max retries exceeded with url: /v2/bundles (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x042CB810>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat',))
Error: Start the ConductR sandbox with: sandbox run IMAGE_VERSION
```

**CONDUCTR_IP**

```
> set CONDUCTR_IP=10.10.10.10
> >python -m conductr_cli.conduct load visualizer
Retrieving bundle..
Cache directory C:\Users\mj/.conductr/cache has the permissions 777. Setting permissions to 700.
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from C:\Users\mj/.lightbend/commercial.credentials
Retrieving from cache C:\Users\mj/.conductr/cache/visualizer-v2-4bbf7b78508b53645eb4dc7b769e2643c5429767c187f284452905fa25e77b46.zip
Loading bundle to ConductR..
Error: Unable to contact ConductR.
Error: Reason: HTTPConnectionPool(host='10.10.10.10', port=9005): Max retries exceeded with url: /v2/bundles (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03FEB810>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat',))
Error: Start the ConductR sandbox with: sandbox run IMAGE_VERSION
```

**Pull request merged**
